config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'tasks', to: 'tasks#index', as: 'tasks'
  # nieuw task maken in form
  get 'tasks/new', to: 'tasks#new', as: 'new_task'
  # show details of one
  get 'tasks/:id', to: 'tasks#show', as: 'task'

  post 'tasks', to: 'tasks#create', as: 'created_task'

  # updating
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch 'tasks/:id', to: 'tasks#update', as: 'update'

  # destroy
  delete 'tasks/:id', to: 'tasks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    # raise
    @task = Task.new(task_params)
    @task.save!

    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path
  end

  def destroy
    @task.delete
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
  <%= form_for(task) do |t| %>
    <div class="form-group">
      <%= t.label :title %>
      <%= t.text_field :title %>
    </div>

    <div class="form-group">
      <%= t.label :details %>
      <%= t.text_field :details %>
    </div>

    <div class="form-group">
      <%= t.label "task completed?" %> <br />
      <%= t.check_box :completed %> <br />
    </div>

    <%= t.submit class: 'btn btn-primary' %>
  <% end %>

app/views/tasks/edit.html.erb
<div class="container">

  <h1>edit task</h1>

  <%= render 'form', task: @task %>

</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>MY TASKS</h1>

  <% @tasks.each do |t| %>
  <div class="task">

    <div class="form-check">
      <% if t.completed %>
        <input class="form-check-input position-static" type="checkbox" id="blankCheckbox" value="option1" checked >
      <% else %>
          <input class="form-check-input position-static" type="checkbox" id="blankCheckbox" value="option1" >
      <% end %>
    </div>

    <div class="title"> <h6><%= link_to t.title, task_path(t) %></h6></div>

    <div class="trash">
      <%= link_to task_path(t), method: :delete,
      data: { confirm: "Are you sure?" } do %>
      <i class="fa fa-trash" aria-hidden="true"> </i>
      <% end %>
    </div>

  </div>
  <% end %>

<div class="new_task">
<p>  <%= link_to "add new taks", new_task_path %></p></div>

</div>

app/views/tasks/new.html.erb
<div class="container">

  <h1>new task</h1>

  <%= render 'form', task: @task %>

</div>

app/views/tasks/show.html.erb
<div class="container">

  <h1>task details</h1>
  <h4> <%= @task.title %> </h4>
  <h6> <%= @task.details %> </h6>

  <div class="btn btn-light">
    <%= link_to "update this task" , edit_path %>
  </div>

  <p> <%= link_to "tasks", tasks_path %></p>



</div>